fdsfsfds

diff --git a/.github/workflows/mainCI.yml b/.github/workflows/mainCI.yml
--- a/.github/workflows/mainCI.yml
+++ b/.github/workflows/mainCI.yml
@@ -27,9 +27,13 @@ jobs:
         run: |
           exit 1
       - name: Report status
-        if: failure()
         run: |
-          echo "step has status: ${{ steps.fail_me.outcome }}"
+          if ${{ steps.fail_me.outcome == 'failure'}}
+            echo "Build has failed"
+            exit 1
+          else 
+            echo "Build has succeeded or is conditionally allowed to continue"
+            exit 0
 
   second_jobs:
     needs: first_job
